language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
before_install:
  - apt-get update -qq
  - apt-get install -y libhdf5-serial-dev
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - coverage run --source=pyexperiment ./run_tests
  - coverage report -m
# collect coverage statistics
after_success:
  - coveralls --verbose