language: python
python:
  - "2.7"

# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libhdf5-serial-dev
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - coverage run --source=pyexperiment ./run_tests
  - coverage report -m
# collect coverage statistics
after_success:
  - coveralls --verbose