#!/usr/bin/env python
"""Runs code checkers on current directory

Written by Peter Duerr
"""
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division
from __future__ import absolute_import


from subprocess import Popen, PIPE

from pyexperiment.utils.printers import print_blue

CHECKERS = [
    ['pep8', './pyexperiment'],
    ['pep8', './examples'],
    ['pep8', './tests'],
    ['pep8', './lint'],
    ['pylint', './pyexperiment', '--reports=n', '--disable=I0011'],
    ['pylint', './tests', '--reports=n', '--disable=I0011',
     '--ignore-imports=y'],
    ['pylint', './lint', '--reports=n', '--disable=I0011'],
    # ['pylint', './tests', '--reports=n'],
    # ['pylint', './examples', '--reports=n']
]
"""List of checkers to run and their arguments
"""

if __name__ == "__main__":
    for checker in CHECKERS:
        process = Popen(checker, stdout=PIPE)
        header = "Output from %s" % " ".join(checker)
        output = process.communicate()
        message = ""
        for elem in output:
            if elem is not None and not len(elem) == 0:
                message += elem
        if not message == "":
            print_blue(header)
            print_blue("=" * len(header))
            print(message)
            print_blue("=" * len(header))
