#!/usr/bin/env python
"""Runs code checkers on current directory

Written by Peter Duerr
"""

from subprocess import Popen, PIPE

from pyexperiment.utils.printers import print_blue

CHECKERS = [
    ['pep8', './pyexperiment'],
    ['pep8', './examples'],
    ['pep8', './tests'],
    ['pylint', './pyexperiment', '--reports=n', '--disable=I0011'],
    #['pylint', './tests', '--reports=n'],
    #['pylint', './examples', '--reports=n']
]
"""List of checkers to run and their arguments
"""

if __name__ == "__main__":
    for checker in CHECKERS:
        process = Popen(checker, stdout=PIPE)
        msg = "Running %s" % " ".join(checker)
        print_blue(msg)
        print_blue("=" * len(msg))
        output = process.communicate()
        for elem in output:
            if elem is not None:
                print(elem)
        print_blue("=" * len(msg))
        print_blue("done...\n")
