#!/usr/bin/env python

"""Runs the tests for pyexperiment

Written by Peter Duerr
"""
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division
from __future__ import absolute_import

import unittest
import sys

# Make sure matplotlib is using backend for headless testing
import matplotlib
matplotlib.use('Agg')

def main(argv):
    """Runs all the tests
    """
    verbosity = 1
    if '-v' in argv:
        verbosity = 2

    suite = unittest.TestLoader().discover('tests')
    return unittest.TextTestRunner(verbosity=verbosity).run(suite)

if __name__ == "__main__":
    result = main(sys.argv)
    if result.wasSuccessful():
        exit(0)
    else:
        exit(1)

