#!/usr/bin/env python

"""Runs the tests for pyexperiment

Written by Peter Duerr
"""
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division
from __future__ import absolute_import

import unittest

# Make sure matplotlib is using backend for headless testing
import matplotlib
matplotlib.use('Agg')

if __name__ == "__main__":
    suite = unittest.TestLoader().discover('tests')
    unittest.TextTestRunner(verbosity=2).run(suite)
