#!/usr/bin/env python
"""Illustrates pyexperiment's command line interface with a minmal example.

Running `minmal_cli` will print a short usage message, `minimal_cli
-h` will show more help, `minimal_cli hello` will print 'Hello', and
`minmal_cli world` will print 'World'.
"""

# Sensible imports from the future (optional)
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division
from __future__ import absolute_import

# Import the experiment module for its main function
from pyexperiment import experiment

# Define a couple function
# The functions' docstrings will be used as help text in the cli
def hello():
    """Prints 'hello'
    """
    print("Hello")

def world():
    """Prints 'world'
    """
    print("World")

if __name__ == '__main__':
    # Passing the functions to the main function will set up the functions'
    # names as first level commands and set up the help text.
    experiment.main(commands=[hello, world])
